### ISSUE TITLE
Build failure on SmartOS (6.1)

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#8]
CI run: https://ci.nodejs.org/job/node-test-commit-smartos/9806/nodes=smartos15-64/console

```
  LD_LIBRARY_PATH=/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/lib.host:/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node/src; dtrace -G -xnolibs -s src/node_provider.d "/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node/src/node_dtrace.o" -o "/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node/src/node_dtrace_provider.o"
  touch /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node_dtrace_provider.stamp
dtrace: failed to compile script src/v8ustack.d: line 377: failed to resolve V8DBG_CLASS_SHAREDFUNCTIONINFO__NAME__OBJECT: Unknown variable name
node_dtrace_ustack.target.mk:26: recipe for target '/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node/src/node_dtrace_ustack.o' failed
make[2]: *** [/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node/src/node_dtrace_ustack.o] Error 1
```

/cc @nodejs/platform-smartos

**Comment by geek** [comment]
@targos I'll take a look today

**Comment by misterdjules** [comment]
@targos You can use the following patch to get passed the compilation error: https://gist.github.com/misterdjules/f0bc7b42de7f9ee72e9535f0ce361ea0. The patch itself is not correct though, in the sense that the function position and function names outputted by the DTrace ustack helper are not correct, but I would think it's fine for now. Is that a correct assumption?

**Comment by targos** [comment]
@misterdjules It does not seem quite correct.
I applied your patch: https://github.com/nodejs/node-v8/commit/0bf3f913b84bdfc40942e3dfc2cdb4786a422f3c and now the error is: `dtrace: failed to compile script src/v8ustack.d: line 458: failed to resolve V8DBG_SHAREDFUNCTION_FUNCTION_TOKEN_POSITION: Unknown variable name`

CI run: https://ci.nodejs.org/job/node-test-commit-smartos/9836/nodes=smartos15-64/console

**Comment by misterdjules** [comment]
@targos 

My apologies, I had forgotten to update the gist with all my local changes. I did so now, and using that gist should now allow you to work around the build errors.

When is that version of V8 scheduled to be merged in master?

**Comment by targos** [comment]
@misterdjules Thank you. V8 6.1 should be merged in early September.

**Comment by targos** [comment]
@misterdjules V8 master is now working on version 6.2. When the correct patch is upstreamed, it will have to be merged back to 6.1.

**Comment by misterdjules** [comment]
@targos If that's fine with the V8 team then that's fine by me. Hopefully I can get to this sooner than later.

**Comment by cjihrig** [comment]
@targos, per my comment at https://github.com/nodejs/node/pull/14730#issuecomment-326062779. I've been able to get postmortem stack traces mostly working in llnode. There is still one problem I'm seeing, and I'm not entirely sure if this is a bug in the postmortem data generation, or something else in V8. Take this code for example:

```js
'use strict';
const fs = require('fs');

fs.readFile(__filename, function readFileCb(err) {
  process.abort();
});
```

Without my changes, the JS stack frames show up in llnode as:

```
    frame #8: 0x00003191fd68463d <exit>
    frame #9: 0x00003191fd7744c9 <stub>
    frame #10: 0x00003191fd73f9ce <builtin>
    frame #11: 0x00003191fd685d1b <adaptor>
    frame #12: 0x00003191fd775002 <stub>
    frame #13: 0x00003191fd73f9ce <builtin>
    frame #14: 0x00003191fd73e479 <internal>
    frame #15: 0x00003191fd68410d <entry>
```

With my changes, those same frames look like:

```
    frame #8: 0x00003191fd68463d <exit>
    frame #9: 0x00003191fd7744c9 <stub>
    frame #10: 0x00003191fd73f9ce readFileCb(this=0x000001e7eaf02311:<undefined>, 0x000001e7eaf02201:<null>) at (no script):4:44 fn=0x000001e7055d5451
    frame #11: 0x00003191fd685d1b <adaptor>
    frame #12: 0x00003191fd775002 <stub>
    frame #13: 0x00003191fd73f9ce readFileAfterClose(this=0x000001e7055d6119:<Object: FSReqWrap>, 0x000001e7eaf02201:<null>) at fs.js:485:28 fn=0x000001e72f930fe1
    frame #14: 0x00003191fd73e479 <internal>
    frame #15: 0x00003191fd68410d <entry>
```

Notice that `fs.js` is properly identified as the source for `readFileAfterClose()`, but my own `readFileCb()` comes from `(no script)`. Now, llnode reads both of these values from the same offset in their respective `Script` data structure, so I'm not sure why one has a value, and the other doesn't.

I'm open to any suggestions you or anyone else might have. Other than that, I think I'm just about ready to upstream my changes.
