### ISSUE TITLE
Port cppgc config to gyp

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#161]
V8 now depends on it. We need to port the config to our GYP files

**Comment by targos** [comment]
I fixed the build at least on Linux with https://github.com/nodejs/node/commit/4ba0b28ef59dcebe6a17713554aec4cd37fff84a and https://github.com/nodejs/node/commit/ac8fb3faa944217e643cce111801da648579600d.
Let's keep this issue open because cppgc is still a moving target and I did not look into implementing the build options that it provides.

**Comment by targos** [comment]
CI: https://ci.nodejs.org/job/node-test-commit-node-v8/546/

Need to fix cross-compilation: 

```
19:41:52 python ./configure --verbose  --dest-cpu=arm
19:41:55 gyp: Dependency '/home/iojs/build/workspace/node-cross-compile/tools/v8_gypfiles/v8.gyp:cppgc_base#host' not found while trying to load target /home/iojs/build/workspace/node-cross-compile/tools/v8_gypfiles/v8.gyp:v8_base_without_compiler#host
```

And macOS:

```
19:41:43 running: 
19:41:43     python tools/gyp_node.py --no-parallel -Dconfiguring_node=1 -f make-mac
19:41:43 static library v8_base_without_compiler has several files with the same basename:
19:41:43   allocation: ../../deps/v8/src/utils/allocation.cc ../../deps/v8/src/heap/cppgc/allocation.cc
19:41:43   free-list: ../../deps/v8/src/heap/free-list.cc ../../deps/v8/src/heap/cppgc/free-list.cc
19:41:43   sweeper: ../../deps/v8/src/heap/sweeper.cc ../../deps/v8/src/heap/cppgc/sweeper.cc
19:41:43   heap: ../../deps/v8/src/heap/heap.cc ../../deps/v8/src/heap/cppgc/heap.cc
19:41:43 libtool on OS X will generate warnings for them.
19:41:43 Error running GYP
19:41:43 make: *** [build-ci] Error 1
```

And Windows:
```
19:46:05   cpp-heap.cc
19:46:05 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xutility(3778,16): error C2280: 'std::unique_ptr<cppgc::internal::BaseSpace,std::default_delete<cppgc::internal::BaseSpace>> &std::unique_ptr<cppgc::internal::BaseSpace,std::default_delete<cppgc::internal::BaseSpace>>::operator =(const std::unique_ptr<cppgc::internal::BaseSpace,std::default_delete<cppgc::internal::BaseSpace>> &)': attempting to reference a deleted function [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
19:46:05 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1917): message : see declaration of 'std::unique_ptr<cppgc::internal::BaseSpace,std::default_delete<cppgc::internal::BaseSpace>>::operator =' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
19:46:05 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1917,17): message : 'std::unique_ptr<cppgc::internal::BaseSpace,std::default_delete<cppgc::internal::BaseSpace>> &std::unique_ptr<cppgc::internal::BaseSpace,std::default_delete<cppgc::internal::BaseSpace>>::operator =(const std::unique_ptr<cppgc::internal::BaseSpace,std::default_delete<cppgc::internal::BaseSpace>> &)': function was explicitly deleted [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
19:46:05 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\vector(1127): message : see reference to function template instantiation '_OutIt *std::_Copy_unchecked<_Iter,std::unique_ptr<cppgc::internal::BaseSpace,std::default_delete<cppgc::internal::BaseSpace>>*>(_InIt,_InIt,_OutIt)' being compiled [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
```

/cc @nodejs/v8

**Comment by ryzokuken** [comment]
The ARM issue doesn't look like a platform-specific error?

**Comment by gengjiawen** [comment]
Windows build actually success on v16.5.5, but failed on v16.6.2.

**Comment by targos** [comment]
I pushed a few fixes. New CI: https://ci.nodejs.org/job/node-test-commit-node-v8/551/

**Comment by gengjiawen** [comment]
Windows still failed on latest vs2019 (works on vs2017, vs2019 v16.5.5), not sure is this a regression.

![image](https://user-images.githubusercontent.com/3759816/85924490-48f05700-b8c5-11ea-840d-dc214108ea74.png)

**Comment by targos** [comment]
I did not do anything for Windows. I don't know if it's a bug in the compiler or in V8

**Comment by targos** [comment]
@nodejs/platform-windows PTAL: https://ci.nodejs.org/job/node-compile-windows/34716/

**Comment by gengjiawen** [comment]
> I did not do anything for Windows. I don't know if it's a bug in the compiler or in V8

I tend to a compiler bug, but I simulate related code but still failed to create a repro :(

**Comment by gengjiawen** [comment]
I pushed a possible fix, now run into lots of unresolved external symbol. cc @targos 
 https://github.com/gengjiawen/node-v8/runs/815584612?check_suite_focus=true#step:6:3810

```console
v8_base_without_compiler.lib(code-generator-x64.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
v8_initializers.lib(builtins-regexp-gen.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
v8_initializers.lib(v8_pch.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
v8_initializers.lib(code-stub-assembler.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
v8_base_without_compiler.lib(instruction-selector-x64.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
v8_initializers.lib(builtins-constructor-gen.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
v8_initializers.lib(builtins-string-gen.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
```

**Comment by gengjiawen** [comment]
> I pushed a possible fix, now run into lots of unresolved external symbol. cc @targos
> [gengjiawen/node-v8/runs/815584612?check_suite_focus=true#step:6:3810](https://github.com/gengjiawen/node-v8/runs/815584612?check_suite_focus=true#step:6:3810)
> 
> ```
> v8_base_without_compiler.lib(code-generator-x64.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
> v8_initializers.lib(builtins-regexp-gen.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
> v8_initializers.lib(v8_pch.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
> v8_initializers.lib(code-stub-assembler.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
> v8_base_without_compiler.lib(instruction-selector-x64.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
> v8_initializers.lib(builtins-constructor-gen.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
> v8_initializers.lib(builtins-string-gen.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Malloced::operator delete(void *)" (??3Malloced@internal@v8@@SAXPEAX@Z) [D:\a\node-v8\node-v8\tools\v8_gypfiles\mksnapshot.vcxproj]
> ```

Is this similar to https://github.com/nodejs/node-v8/issues/126#issuecomment-575111775 cc @targos

**Comment by targos** [comment]
Maybe? But I don't see any syntax error in the changes to the gyp files this time.

**Comment by gengjiawen** [comment]
I have report this to in https://bugs.chromium.org/p/v8/issues/detail?id=10691.

**Comment by gengjiawen** [comment]
I made some progress on https://github.com/gengjiawen/node-v8/tree/vs2019-build, still left some Error LNK2019 error.

**Comment by gengjiawen** [comment]
Can we make cppgc optional for now.

From https://chromium.googlesource.com/v8/v8.git/+/HEAD/include/cppgc/
```
This directory provides an open-source garbage collection library for C++.

The library is under construction, meaning that all APIs in this directory are incomplete and considered unstable and should not be used.
```

**Comment by targos** [comment]
@gengjiawen I don't think we can. It's now a mandatory dependency to build V8 itself.

**Comment by gengjiawen** [comment]
> I have report this to in [bugs.chromium.org/p/v8/issues/detail?id=10691](https://bugs.chromium.org/p/v8/issues/detail?id=10691).

Quick update, fix two issues in upstream (one is https://bugs.chromium.org/p/v8/issues/detail?id=10691#c10, not sure how v8 team find it, I find it by using /P, not sure v8 team using the same).

I believe only one issue (linker issue) is left, I have got an idea, need time to verify it.

**Comment by gengjiawen** [comment]
I have fixed all the issue, successful build can see here. I will try to push related change to upstream.

**Comment by targos** [comment]
Maybe we're hitting [this issue](https://stackoverflow.com/a/9351193). i.e. we are overwriting files because the outputs are all in the same directory? That can probably be fixed somehow in `v8.gyp`

**Comment by gengjiawen** [comment]
> Maybe we're hitting [this issue](https://stackoverflow.com/a/9351193). i.e. we are overwriting files because the outputs are all in the same directory? That can probably be fixed somehow in `v8.gyp`

Looks like it, can this be done by gyp config ?

**Comment by gengjiawen** [comment]
Looks like gyp not support this. https://github.com/nodejs/node-gyp/issues/1424

**Comment by Horcrux7** [comment]
What is the status of this issues? If I understand it correctly then the tool gyp does not support the latest changes of the V8 project. 

Is the project dead now?

**Comment by gengjiawen** [comment]
> What is the status of this issues? If I understand it correctly then the tool gyp does not support the latest changes of the V8 project.
> 
> Is the project dead now?

Nope, we have a backup plan (port related change manually to Node.js). But in the long run we need to fix this in  https://github.com/nodejs/gyp-next or switch to clang maybe.

**Comment by Horcrux7** [comment]
Sounds like a long-term task, months or years.

**Comment by gengjiawen** [comment]
> Sounds like a long-term task, months or years.

We have confidence to keep latest stable v8 release to Node.js, if that's what you worry about.
And also welcome to anyone to help with on this windows issue.

**Comment by Horcrux7** [comment]
No, I want use the canary version to try and develop for the WebAssembly/GC feature. This is currently under daily feature improvement in V8. I will rethink my working now.

**Comment by vsemozhetbyt** [comment]
Sorry to bother, but is it worth to mention the Windows collaborator team here? We have not had Windows canary for three months...

**Comment by gengjiawen** [comment]
> Sorry to bother, but is it worth to mention the Windows collaborators team here? We have not had Windows canary for three months...

This is more like a gyp issue: https://github.com/nodejs/gyp-next/issues/60

**Comment by mhdawson** [comment]
@miladfarca could you take a look at  cppgc so we understand how it might impact power/s390 in the future?

**Comment by vsemozhetbyt** [comment]
nodejs/gyp-next#60 seems fixed but there are no canaries at all for last days.

**Comment by targos** [comment]
> [nodejs/gyp-next#60](https://github.com/nodejs/gyp-next/issues/60) seems fixed but there are no canaries at all for last days.

Canary needed an update in `v8.gyp`. I'm testing it locally.

**Comment by miladfarca** [comment]
@mhdawson It's a new mark and sweep GC called `Oilpan`. It does conservative stack scanning of C++/JS objects (treats them as one heap). It's actively being worked on and any port to other platforms will also get ported to p/z linux and AIX:
https://chromium-review.googlesource.com/c/v8/v8/+/2144691

This also elliminates the use of a clang plugin: https://github.com/nodejs/node/issues/27257#issuecomment-653435140

**Comment by vsemozhetbyt** [comment]
Something seems break all builds again. IIUC, https://github.com/nodejs/node-v8/issues/167

**Comment by vsemozhetbyt** [comment]
Still no Windows in today's build(

**Comment by targos** [comment]
@vsemozhetbyt there's a build failure in release CI, but it seems unrelated to this issue. I opened https://github.com/nodejs/node-v8/issues/172

**Comment by mhdawson** [comment]
@miladfarca thanks for the clarification :)

**Comment by gengjiawen** [comment]
> Still no Windows in today's build(

@vsemozhetbyt windows fix got merged, binary should be on the way 🎁

**Comment by vsemozhetbyt** [comment]
Thank you all! [Win-x64 is back](https://nodejs.org/download/v8-canary/v15.0.0-v8-canary202009173b56586162/).

Now I can publish my translation about Intl.Segmenter (shipped in V8 87) and link to the  full binaries set for readers to test the feature)

Are Win-x86 binaries not built anymore or is this a build issue? [There were ones in the last successful build](https://nodejs.org/download/v8-canary/v15.0.0-v8-canary20200603908772e6f4/).

**Comment by targos** [comment]
x86 build still fails: 

```
05:31:36      Creating library ..\..\out\Release\mksnapshot.lib and object ..\..\out\Release\mksnapshot.exp
05:31:37 mksnapshot.obj : error LNK2019: unresolved external symbol "public: void __thiscall v8::internal::FixedArray::set(int,class v8::internal::Smi)" (?set@FixedArray@internal@v8@@QAEXHVSmi@23@@Z) referenced in function "protected: void __thiscall v8::internal::OrderedHashTable<class v8::internal::OrderedHashMap,2>::SetNumberOfBuckets(int)" (?SetNumberOfBuckets@?$OrderedHashTable@VOrderedHashMap@internal@v8@@$01@internal@v8@@IAEXH@Z) [c:\ws\tools\v8_gypfiles\mksnapshot.vcxproj]
05:31:37 v8_base_without_compiler.lib(stack.obj) : error LNK2019: unresolved external symbol _PushAllRegistersAndIterateStack referenced in function "public: void __thiscall heap::base::Stack::IteratePointers(class heap::base::StackVisitor *)const " (?IteratePointers@Stack@base@heap@@QBEXPAVStackVisitor@23@@Z) [c:\ws\tools\v8_gypfiles\mksnapshot.vcxproj]
05:31:37 ..\..\out\Release\mksnapshot.exe : fatal error LNK1120: 2 unresolved externals [c:\ws\tools\v8_gypfiles\mksnapshot.vcxproj]
```

**Comment by gengjiawen** [comment]
> x86 build still fails:
> 
> ```
> 05:31:36      Creating library ..\..\out\Release\mksnapshot.lib and object ..\..\out\Release\mksnapshot.exp
> 05:31:37 mksnapshot.obj : error LNK2019: unresolved external symbol "public: void __thiscall v8::internal::FixedArray::set(int,class v8::internal::Smi)" (?set@FixedArray@internal@v8@@QAEXHVSmi@23@@Z) referenced in function "protected: void __thiscall v8::internal::OrderedHashTable<class v8::internal::OrderedHashMap,2>::SetNumberOfBuckets(int)" (?SetNumberOfBuckets@?$OrderedHashTable@VOrderedHashMap@internal@v8@@$
01@internal@v8@@IAEXH@Z) [c:\ws\tools\v8_gypfiles\mksnapshot.vcxproj]
> 05:31:37 v8_base_without_compiler.lib(stack.obj) : error LNK2019: unresolved external symbol _PushAllRegistersAndIterateStack referenced in function "public: void __thiscall heap::base::Stack::IteratePointers(class heap::base::StackVisitor *)const " (?IteratePointers@Stack@base@heap@@QBEXPAVStackVisitor@23@@Z) [c:\ws\tools\v8_gypfiles\mksnapshot.vcxproj]
> 05:31:37 ..\..\out\Release\mksnapshot.exe : fatal error LNK1120: 2 unresolved externals [c:\ws\tools\v8_gypfiles\mksnapshot.vcxproj]

@targos loos like you forget the patch x32 to ia32 patch in v8 8.5.

**Comment by targos** [comment]
@gengjiawen right, good catch! I pushed the change to canary-base. Build should go well tomorrow.

**Comment by gengjiawen** [comment]
V8 8.6 merged into core.
