### ISSUE TITLE
Linker errors on `test-linux` action

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#290]
I thought it was due to missing includes so I added some in https://github.com/nodejs/node-v8/commit/3d0e2aee2ec7fdad2298d672b812234111ee9e63, but the errors remain:

https://github.com/nodejs/node-v8/actions/runs/10788009205/job/29917856466

```
2024-09-10T09:32:08.5123584Z /usr/bin/ld: /home/runner/work/node-v8/node-v8/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/execution/isolate.o: in function `v8::internal::Isolate::~Isolate()':
2024-09-10T09:32:08.5125580Z isolate.cc:(.text._ZN2v88internal7IsolateD2Ev+0x3ff): undefined reference to `__atomic_compare_exchange'
2024-09-10T09:32:08.5126892Z /usr/bin/ld: isolate.cc:(.text._ZN2v88internal7IsolateD2Ev+0x4df): undefined reference to `__atomic_compare_exchange'
2024-09-10T09:32:08.5129081Z /usr/bin/ld: isolate.cc:(.text._ZN2v88internal7IsolateD2Ev+0x5bf): undefined reference to `__atomic_compare_exchange'
2024-09-10T09:32:08.5131627Z /usr/bin/ld: /home/runner/work/node-v8/node-v8/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/execution/isolate.o: in function `v8::internal::wasm::WasmCodePointerTable::AllocateUninitializedEntry()':
2024-09-10T09:32:08.5134385Z isolate.cc:(.text._ZN2v88internal4wasm20WasmCodePointerTable26AllocateUninitializedEntryEv[_ZN2v88internal4wasm20WasmCodePointerTable26AllocateUninitializedEntryEv]+0x4b): undefined reference to `__atomic_compare_exchange'
2024-09-10T09:32:08.5137023Z /usr/bin/ld: isolate.cc:(.text._ZN2v88internal4wasm20WasmCodePointerTable26AllocateUninitializedEntryEv[_ZN2v88internal4wasm20WasmCodePointerTable26AllocateUninitializedEntryEv]+0x12e): undefined reference to `__atomic_compare_exchange'
2024-09-10T09:32:08.6131002Z /usr/bin/ld: /home/runner/work/node-v8/node-v8/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/wasm/wasm-code-manager.o:wasm-code-manager.cc:(.text._ZN2v88internal4wasm8WasmCodeD2Ev+0xab): more undefined references to `__atomic_compare_exchange' follow
2024-09-10T09:32:09.2511911Z clang++: error: linker command failed with exit code 1 (use -v to see invocation)
2024-09-10T09:32:09.2553728Z make[2]: *** [tools/v8_gypfiles/mksnapshot.target.mk:220: /home/runner/work/node-v8/node-v8/out/Release/mksnapshot] Error 1
```

**Comment by richardlau** [comment]
>```
> undefined reference to `__atomic_compare_exchange'
>```

Perhaps the version of `clang` being used in Actions requires libatomic?

**Comment by lemire** [comment]
The following reference seems relevant:

https://clang.llvm.org/docs/Toolchain.html#libatomic-gnu

I think @richardlau is correct, here is what LLVM docs say:

> You may need to manually add -latomic

**Comment by richardlau** [comment]
I can only assume something has changed in V8 13.0 compared to 12.9. The stack from the linker in the description is suggesting that it's coming from `v8::internal::Isolate::~Isolate()` calling into `WasmCodePointerTable`, which looks to be https://github.com/v8/v8/commit/21664908a3940ab926ddb145dfcb833f5554cdf2#diff-76761d277cce95bd9f0a3f0d836f94f36bfbd32b1026c247faf32acbcd67a625

`WasmCodePointerTable` looks to be new, introduced in https://github.com/v8/v8/commit/0b1d09be468c020881d0d36b1f288702453faad9.

**Comment by targos** [comment]
After reading https://clang.llvm.org/docs/Toolchain.html#libatomic-gnu, I understand that Clang apparently does not always require `-latomic`.
I'm trying to fix this in https://github.com/nodejs/node/pull/55014 (https://github.com/nodejs/node/pull/55014/commits/d48a069c66051750851b72a522fd2c4c7f4544ab)

**Comment by targos** [comment]
Build looks good. I'm adding the commit to `canary-base`
