### ISSUE TITLE
Build failure on AIX

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#29]
CI run: https://ci.nodejs.org/job/node-test-commit-aix/10778/nodes=aix61-ppc64/console

Error:
```
../deps/v8/src/base/platform/platform-posix.cc: In function 'int v8::base::{anonymous}::ReclaimInaccessibleMemory(void*, size_t)':
../deps/v8/src/base/platform/platform-posix.cc:141:37: error: invalid conversion from 'void*' to 'caddr_t {aka char*}' [-fpermissive]
   int ret = madvise(address, size, MADV_FREE);
                                     ^
In file included from ../deps/v8/src/base/platform/platform-posix.cc:20:0:
/usr/include/sys/mman.h:187:13: error:   initializing argument 1 of 'int madvise(caddr_t, size_t, int)' [-fpermissive]
  extern int  madvise(caddr_t, size_t, int);
             ^
../deps/v8/src/base/platform/platform-posix.cc:147:35: error: invalid conversion from 'void*' to 'caddr_t {aka char*}' [-fpermissive]
     ret = madvise(address, size, MADV_DONTNEED);
                                   ^
In file included from ../deps/v8/src/base/platform/platform-posix.cc:20:0:
/usr/include/sys/mman.h:187:13: error:   initializing argument 1 of 'int madvise(caddr_t, size_t, int)' [-fpermissive]
  extern int  madvise(caddr_t, size_t, int);
             ^

```

@nodejs/platform-aix

**Comment by targos** [comment]
Introduced in https://github.com/v8/v8/commit/2cbfa2444d6192b472f02cab2c0f25b9df6145fb

**Comment by gireeshpunathil** [comment]
madvise on Linux:
int madvise(void *addr, size_t length, int advice);

madvise on AIX:
int madvise(caddr_t addr, size_t len,  int behav)
where:
typedef char * caddr_t;


So I guess we just need to cast addr (that is void *) to caddr_t for AIX.

can you please try this patch?

```patch
--- a/deps/v8/src/base/platform/platform-posix.cc
+++ b/deps/v8/src/base/platform/platform-posix.cc
@@ -137,6 +137,8 @@ int ReclaimInaccessibleMemory(void* address, size_t size) {
   // marks the pages with the reusable bit, which allows both Activity Monitor
   // and memory-infra to correctly track the pages.
   int ret = madvise(address, size, MADV_FREE_REUSABLE);
+#elif defined(_AIX)
+  int ret = madvise((caddr_t) address, size, MADV_FREE);
 #else
   int ret = madvise(address, size, MADV_FREE);
 #endif
@@ -144,7 +146,11 @@ int ReclaimInaccessibleMemory(void* address, size_t size) {
     // MADV_FREE only works on Linux 4.5+ . If request failed, retry with older
     // MADV_DONTNEED . Note that MADV_FREE being defined at compile time doesn't
     // imply runtime support.
+#if defined(_AIX)
+    ret = madvise((caddr_t) address, size, MADV_DONTNEED);
+#else
     ret = madvise(address, size, MADV_DONTNEED);
+#endif
   }
   return ret;
 }
```

**Comment by targos** [comment]
Sure: https://ci.nodejs.org/job/node-test-commit-aix/10782/

**Comment by gibfahn** [comment]
Job is green! @gireeshpunathil I know you're on holiday, maybe someone could upstream this patch for you.

**Comment by gireeshpunathil** [comment]
please feel free to upstream, @targos / @gibfahn

**Comment by mhdawson** [comment]
@jBarz you could possibly also get Junliang to help upstream unless @targos can do it easily.

**Comment by jBarz** [comment]
Upstream underway [here](https://chromium-review.googlesource.com/c/v8/v8/+/804554)

**Comment by targos** [comment]
Fix landed upstream: https://github.com/v8/v8/commit/3c5cb5e5c77b9aed4e0cb5a9bce14c381af26699.
Thank you!
